masscan:
  max-rate: 1000000
  excludeconfPath: schedules/masscan_config/exclude.conf
postgresql:
  host: localhost
  port: 5432
  user: ssreborn_user
  password: ssreborn_password
  database: ssreborn_db
redis:
  host: localhost
  port: 6379


  