services:
  database:
    image: postgres
    container_name: ssreborn-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ssreborn_user
      POSTGRES_PASSWORD: ssreborn_password
      POSTGRES_DB: ssreborn_db
    volumes:
      - ./ssreborn-db-data:/var/lib/postgresql/data
    networks:
      ssreborn-network:
        ipv4_address: 172.20.0.3
      ssreborn-external-network: {}
        
  redis:
    image: redis:latest
    container_name: ssreborn-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./ssreborn-redis-data:/data
    networks:
      ssreborn-network:
        ipv4_address: 172.20.0.4
      ssreborn-external-network: {}

  adminer:
    image: adminer
    container_name: ssreborn-adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      ssreborn-network:
        ipv4_address: 172.20.0.5
      ssreborn-external-network: {}

networks:
  ssreborn-network:
    ipam:
     config:
       - subnet: 172.20.0.0/16
         gateway: 172.20.0.1
  ssreborn-external-network:
    external: true
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1
    
