version: '3'
services:
  database:
    image: postgres
    container_name: ssreborn-db
    restart: always
    environment:
      POSTGRES_USER: ssreborn_user
      POSTGRES_PASSWORD: ssreborn_password
      POSTGRES_DB: ssreborn_db
  adminer:
    image: adminer
    container_name: ssreborn-adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - ssreborn-network
    depends_on:
      - database
networks:
  ssreborn-network:
    external: true
